### ISSUE TITLE
ImportError: cannot import name render_view

### ISSUE THREAD

**Issue by vaibhavmule** [minervaproject/pykurento#4]
@genehallman I just git pulled and while trying run the app i got this error. 

`Traceback (most recent call last):`
 `File "app.py", line 14, in <module>`
   `from examples import render_view`
`ImportError: cannot import name render_view`
`

**Comment by genehallman** [comment]
Thanks for the heads up - I'll look into fixing this.
How are you running the example app?
Are you cd'ing into examples then running ./app.py?
Or are you running ./examples/app.py from the root of the repo?

I've updated the docs to reflect how I've refactored the examples - I assumed this should work either way, but with your info I'm guessing I'm wrong.

**Comment by vaibhavmule** [comment]
Both way happening same. I thought it might be happening because of Pykurento pip packages has been installed. After that, I have created virtual environment.

If I run in both way, now I'm getting this error.
`Traceback (most recent call last):`
  `File "./app.py", line 14, in <module>`
   `from examples import render_view`
 `File "/home/vaibhav/work/pykurento/examples/__init__.py", line 9, in <module>`
   `from pykurento import KurentoClient`
  `File "/home/vaibhav/work/pykurento/pykurento/__init__.py", line 1, in <module>`
    `from client import KurentoClient`
  `File "/home/vaibhav/work/pykurento/pykurento/client.py", line 2, in <module>`
    `from pykurento.transport import KurentoTransport`
 `File "/home/vaibhav/work/pykurento/pykurento/transport.py", line 1, in <module>`
    `import websocket`
 `File "/home/vaibhav/work/pykurento/examples/venv/local/lib/python2.7/site-packages/websocket/__init__.py", line 21, in <module>`
    `from ._core import *`
  `File "/home/vaibhav/work/pykurento/examples/venv/local/lib/python2.7/site-packages/websocket/_core.py", line 24, in <module>`
   `import six`
`ImportError: No module named six`

**Comment by vaibhavmule** [comment]
This issue has been solved. I'm sorry, it was dependency issue.
