### ISSUE TITLE
Cant find an example of creating kurento composite and hub ports

### ISSUE THREAD

**Issue by CheyenneForbes** [minervaproject/pykurento#7]
can anyone show my an example or explain how I would do these?

**Comment by genehallman** [comment]
Hey, sorry, I haven't been actively working on this project for quite some time.
I'll see what I can dig up, I'm pretty sure i got it working at some point.

Also, are you interested in taking over this project moving forward?
For the moment we're focusing our efforts on licode as it seems to be more stable.

**Comment by CheyenneForbes** [comment]
yes, I am interested in taking over the project
